import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy & Terms — MyNextDeveloper",
  description:
    "Privacy Policy, Terms of Service, and Data Protection information for MND Technologies Private Limited.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#faf7f2]">
      <header className="bg-navy px-5 py-4 sm:px-8">
        <Link
          href="/"
          className="text-[13px] font-medium text-white/70 transition hover:text-white"
        >
          ← Back
        </Link>
      </header>

      <main className="mx-auto max-w-[800px] px-5 py-10 sm:px-8 md:py-16">
        <div className="mb-10 border-b border-navy/10 pb-8">
          <p className="mb-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#444443]/60">
            MND Technologies Private Limited
          </p>
          <h1 className="mb-3 font-serif text-[clamp(32px,7vw,48px)] font-medium leading-[1.08] tracking-[-0.01em] text-navy">
            Privacy Policy &amp;{" "}
            <em className="font-medium italic text-teal">Terms</em>
          </h1>
          <p className="text-[13.5px] text-[#444443]/70">
            Last Updated: May 2026 &nbsp;·&nbsp;{" "}
            <a
              href="mailto:ops@mynextdeveloper.com"
              className="text-teal underline underline-offset-2 hover:text-navy"
            >
              ops@mynextdeveloper.com
            </a>
          </p>
        </div>

        <div className="space-y-10 text-[15px] leading-[1.7] text-[#333]">

          {/* PART 1 */}
          <Part label="Part 1" title="Core Privacy Policy" />

          <Section id="1" title="Introduction">
            <p>
              MyNextDeveloper, operated by MND Technologies Private Limited
              (&ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;),
              operates{" "}
              <a href="https://mynextdeveloper.com" className="link">
                https://mynextdeveloper.com
              </a>{" "}
              (the &ldquo;Service&rdquo;).
            </p>
            <p>
              Our Privacy Policy governs your visit to{" "}
              <a href="https://mynextdeveloper.com" className="link">
                https://mynextdeveloper.com
              </a>{" "}
              and explains how we collect, safeguard, and disclose information
              that results from your use of our Service. We use your data to
              provide and improve the Service. By using the Service, you agree
              to the collection and use of information in accordance with this
              policy. Our Terms and Conditions (&ldquo;Terms&rdquo;) govern all
              use of our Service and, together with this Privacy Policy,
              constitute your agreement with us (&ldquo;Agreement&rdquo;).
            </p>
          </Section>

          <Section id="2" title="Definitions">
            <dl className="space-y-3">
              {[
                ["SERVICE", "The https://mynextdeveloper.com website operated by us."],
                ["PERSONAL DATA", "Data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession)."],
                ["USAGE DATA", "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit)."],
                ["COOKIES", "Small files stored on your device (computer or mobile device)."],
                ["CANDIDATE", "The person introduced/re-introduced by us to the Client for an Engagement."],
                ["CLIENT", "The person introduced/re-introduced by us to the Candidate for an Engagement."],
                ["DATA CONTROLLER", "A natural or legal person who determines the purposes for which and how any personal data are processed. For this Privacy Policy, we are a Data Controller of your data."],
                ["DATA PROCESSORS (OR SERVICE PROVIDERS)", "Any natural or legal person who processes the data on behalf of the Data Controller."],
                ["DATA SUBJECT", "Any living individual who is the subject of Personal Data."],
                ["THE USER", "The individual using our Service, corresponding to the Data Subject."],
              ].map(([term, def]) => (
                <div key={term}>
                  <dt className="font-semibold text-navy">{term}</dt>
                  <dd className="mt-0.5 text-[#444443]">{def}</dd>
                </div>
              ))}
            </dl>
          </Section>

          <Section id="3" title="Information Collection and Use">
            <p>
              We collect several different types of information for various
              purposes to provide and improve our Service to you.
            </p>
          </Section>

          <Section id="4" title="Types of Data Collected">
            <h3 className="mb-1 font-semibold text-navy">Personal Data</h3>
            <p>
              While using our Service, we may ask you to provide us with
              certain personally identifiable information that can be used to
              contact or identify you. This may include, but is not limited to:
            </p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Email address</li>
              <li>Name</li>
              <li>Phone Number</li>
              <li>Cookies and Usage Data</li>
            </ul>
            <p>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out by emailing{" "}
              <a href="mailto:ops@mynextdeveloper.com" className="link">
                ops@mynextdeveloper.com
              </a>
              .
            </p>
            <h3 className="mb-1 mt-4 font-semibold text-navy">Usage Data</h3>
            <p>
              We may also collect information your browser sends whenever you
              visit our Service. This may include your IP address, browser type
              and version, pages visited, time and date of visit, time spent on
              pages, unique device identifiers, and other diagnostic data.
            </p>
            <h3 className="mb-1 mt-4 font-semibold text-navy">
              Tracking &amp; Cookies Data
            </h3>
            <p>
              We use cookies and similar tracking technologies to track
              activity on our Service. You can instruct your browser to refuse
              all cookies, though some portions of the Service may not function
              properly as a result. Types of cookies we use:
            </p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Session Cookies — to operate our Service</li>
              <li>Preference Cookies — to remember your preferences and settings</li>
              <li>Security Cookies — for security purposes</li>
            </ul>
          </Section>

          <Section id="5" title="Use of Data">
            <p>MyNextDeveloper uses the collected data to:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Provide and maintain our Service</li>
              <li>Notify you about changes to our Service</li>
              <li>Provide customer support</li>
              <li>Gather analysis to improve our Service</li>
              <li>Monitor usage of our Service</li>
              <li>Detect, prevent, and address technical issues</li>
              <li>Fulfil any other purpose for which you provide it</li>
              <li>Carry out obligations and enforce rights arising from contracts with you</li>
              <li>Provide you with notices about your account and/or subscription</li>
              <li>Send news, special offers, and general information about similar goods or services, unless you have opted out</li>
              <li>For any other purpose with your consent</li>
            </ul>
          </Section>

          <Section id="6" title="Retention of Data">
            <p>
              We will retain your Personal Data only for as long as is
              necessary for the purposes set out in this Privacy Policy. We
              will retain and use your Personal Data to comply with legal
              obligations, resolve disputes, and enforce legal agreements.
            </p>
            <p>
              Usage Data is generally retained for a shorter period, except
              when used to strengthen security or improve functionality, or
              when we are legally obligated to retain it longer.
            </p>
          </Section>

          <Section id="7" title="Access, Correction and Deletion of Information">
            <p>
              You can request for us to remove or modify any information about
              your account. To permanently remove your data, email us at{" "}
              <a href="mailto:ops@mynextdeveloper.com" className="link">
                ops@mynextdeveloper.com
              </a>{" "}
              and we will action your request within 30 days.
            </p>
          </Section>

          <Section id="8" title="Transfer of Data">
            <p>
              Your information, including Personal Data, may be transferred to
              and maintained on computers located outside of your state,
              province, country, or other governmental jurisdiction where data
              protection laws may differ. Your consent to this Privacy Policy
              followed by your submission of such information represents your
              agreement to that transfer.
            </p>
            <p>
              We will take all steps reasonably necessary to ensure your data
              is treated securely and in accordance with this Privacy Policy.
              No transfer of your Personal Data will take place to an
              organisation or country unless adequate controls are in place.
            </p>
          </Section>

          <Section id="9" title="Disclosure of Data">
            <p>
              We may disclose personal information that we collect, or that you
              provide, to fulfil the purpose for which you provide it.
            </p>
          </Section>

          <Section id="10" title="Security of Data">
            <p>
              The security of your data is important to us. While we strive to
              use commercially acceptable means to protect your Personal Data,
              no method of transmission over the Internet or electronic storage
              is 100% secure, and we cannot guarantee absolute security.
            </p>
          </Section>

          <Section id="11" title="GDPR — Your Rights (EU/EEA Users)">
            <p>
              If you are a resident of the European Union or European Economic
              Area, you have data protection rights under GDPR. You have the
              right to:
            </p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Access, update, or delete the information we hold about you</li>
              <li>Rectification — have inaccurate or incomplete information corrected</li>
              <li>Object to our processing of your Personal Data</li>
              <li>Restrict the processing of your personal information</li>
              <li>Data portability — receive a copy of your data in a structured, machine-readable format</li>
              <li>Withdraw consent at any time where we rely on consent to process your information</li>
            </ul>
            <p>
              To exercise any of these rights, email{" "}
              <a href="mailto:ops@mynextdeveloper.com" className="link">
                ops@mynextdeveloper.com
              </a>
              . You also have the right to complain to a Data Protection
              Authority in your jurisdiction.
            </p>
          </Section>

          <Section id="12" title="CalOPPA — California Users">
            <p>According to CalOPPA, we agree to the following:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Users can visit our site anonymously</li>
              <li>Our Privacy Policy link includes the word &ldquo;Privacy&rdquo; and is accessible from the homepage</li>
              <li>Users will be notified of any privacy policy changes on this page</li>
              <li>
                Users are able to update their personal information by emailing{" "}
                <a href="mailto:ops@mynextdeveloper.com" className="link">
                  ops@mynextdeveloper.com
                </a>
              </li>
            </ul>
          </Section>

          <Section id="13" title="Analytics">
            <p>
              We may use third-party Service Providers to monitor and analyse
              the use of our Service, including Google Analytics. Google
              Analytics tracks and reports website traffic; this data is shared
              with other Google services. For more information, visit{" "}
              <a
                href="https://policies.google.com/privacy"
                target="_blank"
                rel="noopener"
                className="link"
              >
                https://policies.google.com/privacy
              </a>
              .
            </p>
          </Section>

          <Section id="14" title="Intellectual Property">
            <p>
              The Service and its original content, features, and functionality
              are and will remain the exclusive property of MyNextDeveloper and
              its licensors. Our trademarks and trade dress may not be used in
              connection with any product or service without our prior written
              consent.
            </p>
          </Section>

          <Section id="15" title="Payments">
            <p>
              Where paid services are offered, we use third-party payment
              processors. We do not store or collect your payment card details.
              Our payment processors adhere to PCI-DSS standards. Processors we
              may use include{" "}
              <a
                href="https://razorpay.com/privacy"
                target="_blank"
                rel="noopener"
                className="link"
              >
                Razorpay
              </a>{" "}
              and{" "}
              <a
                href="https://stripe.com/en-in/privacy"
                target="_blank"
                rel="noopener"
                className="link"
              >
                Stripe
              </a>
              .
            </p>
          </Section>

          <Section id="16" title="Links to Other Sites">
            <p>
              Our Service may contain links to third-party sites. We strongly
              advise you to review the privacy policy of every site you visit.
              We have no control over and assume no responsibility for their
              content, privacy policies, or practices.
            </p>
          </Section>

          <Section id="17" title="Children's Privacy">
            <p>
              Our Services are not intended for use by children under the age
              of 13. We do not knowingly collect personally identifiable
              information from children under 13. If you become aware that a
              child has provided us with Personal Data, please contact us
              immediately.
            </p>
          </Section>

          <Section id="18" title="Changes to This Privacy Policy">
            <p>
              We may update our Privacy Policy at any time. We may notify you
              via email or a prominent notice on our Service. You are advised
              to review this page periodically. Changes are effective when
              posted.
            </p>
          </Section>

          <Section id="19" title="Changes to Service">
            <p>
              We reserve the right to withdraw or amend our Service in our
              sole discretion without notice. We will not be liable if for any
              reason all or part of the Service is unavailable at any time.
            </p>
          </Section>

          <Section id="20" title="Error Reporting and Feedback">
            <p>
              You may provide us with feedback, ideas, suggestions, or
              complaints at{" "}
              <a href="mailto:ops@mynextdeveloper.com" className="link">
                ops@mynextdeveloper.com
              </a>
              . By submitting feedback, you acknowledge that MyNextDeveloper is
              not under any obligation of confidentiality and may use such
              feedback freely.
            </p>
          </Section>

          <Section id="21" title="Governing Law">
            <p>
              These Terms shall be governed and construed in accordance with
              the laws of India without regard to its conflict of law
              provisions. These Terms constitute the entire agreement between
              us regarding the Service.
            </p>
          </Section>

          <Section id="22" title="Disclaimer of Warranty">
            <p className="uppercase text-[13.5px] leading-[1.6]">
              These services are provided by MyNextDeveloper on an &ldquo;as
              is&rdquo; and &ldquo;as available&rdquo; basis without warranties
              of any kind, either express or implied. Your use of these services
              is at your sole risk.
            </p>
          </Section>

          <Section id="23" title="Limitation of Liability">
            <p className="uppercase text-[13.5px] leading-[1.6]">
              Except as prohibited by law, MyNextDeveloper shall not be liable
              for any indirect, punitive, special, incidental, or consequential
              damages. Where liability is found, it will be limited to the
              amount paid for the products and/or services.
            </p>
          </Section>

          <Section id="24" title="Non-Solicitation">
            <p>
              By using our Service, both Candidates and Clients acknowledge
              that they shall not seek to circumvent us or conduct direct
              dealings during the tenure of the contract or for a period of
              twenty-four (24) months from the date of introduction without our
              prior written authorisation. Violation will result in a fee
              equivalent to two (2) times the yearly cost given by us to the
              Client.
            </p>
          </Section>

          <Section id="25" title="Acknowledgement">
            <p className="uppercase text-[13.5px] leading-[1.6]">
              By using the Service, you acknowledge that you have read these
              Terms of Service and agree to be bound by them.
            </p>
          </Section>

          <Section id="26" title="Contact Us">
            <p>If you have any questions about this Privacy Policy:</p>
            <address className="mt-2 not-italic text-[#444443]">
              <strong className="text-navy">Email:</strong>{" "}
              <a href="mailto:ops@mynextdeveloper.com" className="link">
                ops@mynextdeveloper.com
              </a>
              <br />
              <strong className="text-navy">Post:</strong> MND Technologies
              Private Limited, 6, 1st Floor, Kamala Niketan, Dr. Bhagvan
              Indrjit Road, Malabar Hill, Mumbai — 400006
            </address>
          </Section>

          {/* PART 2 */}
          <Part label="Part 2" title="Digital Personal Data Protection Act, 2023 (India)" />

          <Section id="27" title="Overview">
            <p>
              In compliance with India&apos;s Digital Personal Data Protection
              Act, 2023 (&ldquo;DPDP Act&rdquo;), MND Technologies Private
              Limited acts as a Data Fiduciary in respect of the personal data
              of individuals (&ldquo;Data Principals&rdquo;) who interact with
              our services. The DPDP Act came into force in August 2023. As an
              Indian company processing data of Indian citizens, we are bound
              by its provisions.
            </p>
          </Section>

          <Section id="28" title="Lawful Basis for Processing">
            <p>
              We process your personal data only on the following lawful bases
              as defined under the DPDP Act:
            </p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>
                <strong>Consent</strong> — freely given, specific, informed,
                and unambiguous consent from you before processing your personal
                data for purposes not covered by the Act&apos;s exemptions
              </li>
              <li>
                <strong>Legitimate Uses</strong> — processing necessary for the
                performance of a contract, compliance with legal obligations, or
                other uses permitted under the Act
              </li>
            </ul>
            <p>
              Where we rely on consent, you have the right to withdraw it at
              any time. Withdrawal does not affect the lawfulness of processing
              carried out prior to withdrawal.
            </p>
          </Section>

          <Section id="29" title="Rights of Data Principals (You)">
            <p>Under the DPDP Act, you have the following rights:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li><strong>Right to Access</strong> — request a summary of personal data we process about you</li>
              <li><strong>Right to Correction</strong> — request correction of inaccurate or misleading personal data</li>
              <li><strong>Right to Erasure</strong> — request erasure of personal data no longer necessary for its original purpose, subject to legal retention requirements</li>
              <li><strong>Right to Grievance Redressal</strong> — raise a grievance and receive a timely resolution</li>
              <li><strong>Right to Nominate</strong> — nominate another individual to exercise your rights in the event of your death or incapacity</li>
            </ul>
            <p>
              To exercise any of these rights, email{" "}
              <a href="mailto:ops@mynextdeveloper.com" className="link">
                ops@mynextdeveloper.com
              </a>
              . We will respond within the timeframe prescribed under applicable
              law.
            </p>
          </Section>

          <Section id="30" title="Consent Management">
            <p>Where we rely on your consent to process personal data:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>We will provide a clear, plain-language notice describing what data is collected and why</li>
              <li>Consent will be obtained before or at the time of data collection</li>
              <li>You may withdraw consent at any time by contacting <a href="mailto:ops@mynextdeveloper.com" className="link">ops@mynextdeveloper.com</a></li>
              <li>Withdrawal of consent may affect your ability to use certain features of our Service</li>
            </ul>
          </Section>

          <Section id="31" title="Data Localisation & Cross-Border Transfers">
            <p>
              MND Technologies Private Limited may transfer personal data
              outside India in the course of providing services to international
              clients. Such transfers will be conducted in compliance with the
              provisions of the DPDP Act and any rules or regulations issued
              thereunder regarding cross-border data flows.
            </p>
          </Section>

          <Section id="32" title="Grievance Officer (India)">
            <p>
              In accordance with the DPDP Act and the Information Technology
              Act, 2000, we have designated a Grievance Officer for India:
            </p>
            <address className="mt-2 not-italic text-[#444443]">
              <strong className="text-navy">Name:</strong> MND Technologies —
              Operations Team
              <br />
              <strong className="text-navy">Email:</strong>{" "}
              <a href="mailto:ops@mynextdeveloper.com" className="link">
                ops@mynextdeveloper.com
              </a>
              <br />
              <strong className="text-navy">Address:</strong> MND Technologies
              Private Limited, 6, 1st Floor, Kamala Niketan, Dr. Bhagvan
              Indrjit Road, Malabar Hill, Mumbai — 400006
              <br />
              <strong className="text-navy">Response Time:</strong> Within 30
              days of receipt of grievance
            </address>
            <p className="mt-3">
              If you are not satisfied with our response, you may approach the
              Data Protection Board of India once it is constituted and
              operational under the DPDP Act.
            </p>
          </Section>

          <Section id="33" title="Children's Data under DPDP">
            <p>
              Consistent with the DPDP Act, we do not knowingly process
              personal data of children below the age of 18 without verifiable
              parental consent. Our services are not directed at minors. If we
              become aware that personal data of a child has been collected
              without appropriate consent, we will take prompt steps to delete
              such data.
            </p>
          </Section>

          {/* PART 3 */}
          <Part label="Part 3" title="Campaign & Event Data Notice" />

          <Section id="34" title="Scope of This Notice">
            <p>
              This notice applies to any MyNextDeveloper marketing campaigns,
              interactive web experiences, QR code activations, digital ads, or
              event-based landing pages (&ldquo;Campaign Activities&rdquo;). If
              you have reached a MyNextDeveloper page via a QR code, digital
              ad, or physical marketing material, this section is particularly
              relevant to you.
            </p>
          </Section>

          <Section id="35" title="Data Collected Through Campaign Activities">
            <p>When you interact with a Campaign Activity, we may collect:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>IP address and approximate geolocation (city/region level)</li>
              <li>Device type, operating system, and browser information</li>
              <li>Date, time, and duration of your interaction</li>
              <li>Pages visited and actions taken within the campaign experience</li>
              <li>Referral source (e.g., which QR code or ad creative directed you here)</li>
              <li>Any information you voluntarily submit through forms, quizzes, or interactive features</li>
            </ul>
            <p>
              We do not collect sensitive personal information (such as
              financial data, health information, or government-issued ID
              numbers) through Campaign Activities.
            </p>
          </Section>

          <Section id="36" title="How We Use Campaign Data">
            <p>Campaign data is used for:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Measuring the reach and effectiveness of our marketing materials</li>
              <li>Understanding audience engagement with our content</li>
              <li>Improving future campaign design and user experience</li>
              <li>Following up with you if you have voluntarily provided your contact details</li>
              <li>Analysing aggregate, anonymised trends — no individual profiling</li>
            </ul>
          </Section>

          <Section id="37" title="Analytics Tools Used in Campaigns">
            <p>
              Our campaign landing pages may use third-party analytics tools
              including Google Analytics and Vercel Analytics. These tools
              collect usage data on our behalf. We have configured these tools
              to minimise personal data collection wherever possible.
            </p>
          </Section>

          <Section id="38" title="Data Retention — Campaign Data">
            <p>
              Campaign interaction data is retained for a maximum of 12 months
              from the date of the campaign&apos;s conclusion, after which it
              is deleted or anonymised. Contact details voluntarily submitted
              through campaigns are retained until you opt out or request
              deletion.
            </p>
          </Section>

          <Section id="39" title="Your Choices">
            <p>Participation in Campaign Activities is entirely voluntary. You may:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Decline to provide any personal information in forms or interactive features</li>
              <li>Opt out of follow-up communications at any time by emailing <a href="mailto:ops@mynextdeveloper.com" className="link">ops@mynextdeveloper.com</a></li>
              <li>Request deletion of any data collected from your campaign interaction</li>
            </ul>
          </Section>

          {/* PART 4 */}
          <Part label="Part 4" title="Webinar Registration Terms" />

          <Section id="40" title="Scope">
            <p>
              These terms apply to any individual who registers for or attends
              a webinar, live session, workshop, or online event
              (&ldquo;Webinar&rdquo;) hosted or co-hosted by MND Technologies
              Private Limited.
            </p>
          </Section>

          <Section id="41" title="Data Collected at Registration">
            <p>When you register for a Webinar, we collect:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Full name</li>
              <li>Email address</li>
              <li>Phone number (where provided)</li>
              <li>Organisation or company name (where provided)</li>
              <li>Any additional information you choose to provide in registration form fields</li>
            </ul>
            <p>
              By submitting a registration form, you consent to the collection
              and use of this data as described in this section.
            </p>
          </Section>

          <Section id="42" title="How Registration Data is Used">
            <p>Your registration data will be used for:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Sending confirmation and reminder communications about the Webinar</li>
              <li>Providing access links, joining instructions, and session materials</li>
              <li>Following up with session recordings, resources, or related content</li>
              <li>Informing you about future Webinars, events, or services from MyNextDeveloper, where you have provided consent</li>
              <li>Internal analysis to improve event content and delivery</li>
            </ul>
            <p>
              We will not sell, rent, or share your registration data with
              third parties for their own marketing purposes.
            </p>
          </Section>

          <Section id="43" title="Third-Party Platforms">
            <p>
              Our Webinars may be hosted on third-party platforms such as Zoom,
              Google Meet, Microsoft Teams, or similar. By joining a Webinar,
              you agree to the terms and privacy policies of the relevant
              platform. MyNextDeveloper is not responsible for data processing
              carried out by these platforms.
            </p>
            <p>
              Where sessions are recorded, you will be informed at the start of
              the session. Recordings may be shared publicly or with registered
              attendees only, as communicated at the time of registration.
            </p>
          </Section>

          <Section id="44" title="Consent & Opt-Out for Marketing Communications">
            <p>
              By registering for a Webinar, you consent to receiving follow-up
              communications related to that specific event. Ongoing marketing
              communications will only be sent where you have separately opted
              in or where we have a legitimate interest to do so under
              applicable law.
            </p>
            <p>You may opt out of all marketing communications at any time by:</p>
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Clicking the unsubscribe link in any email we send</li>
              <li>Emailing <a href="mailto:ops@mynextdeveloper.com" className="link">ops@mynextdeveloper.com</a> with &ldquo;Unsubscribe&rdquo; in the subject line</li>
            </ul>
            <p>
              Opting out will not affect your ability to receive transactional
              messages related to a Webinar you have already registered for.
            </p>
          </Section>

          <Section id="45" title="Data Retention — Webinar Data">
            <p>
              Webinar registration data is retained for up to 24 months
              following the event date, after which it is deleted or
              anonymised. If you request deletion of your data earlier, we will
              comply within 30 days.
            </p>
          </Section>

          <Section id="46" title="Refund &amp; Cancellation Policy">
            <ul className="my-2 list-disc pl-5 space-y-1">
              <li>Cancellations are accepted up to 5 days before the event; requests after that are not eligible for a refund</li>
              <li>Payment gateway charges are non-refundable. Only the balance amount is refunded</li>
              <li>Approved refunds are processed within 7–10 business days (time to reflect depends on your bank)</li>
              <li>Refunds go back to the original payment method</li>
            </ul>
            <p>
              To cancel and request a refund, email{" "}
              <a href="mailto:ops@mynextdeveloper.com" className="link">
                ops@mynextdeveloper.com
              </a>{" "}
              before the cancellation deadline.
            </p>
          </Section>

          <Section id="47" title="Contact for Webinar Data Queries">
            <address className="not-italic">
              <strong className="text-navy">Email:</strong>{" "}
              <a href="mailto:ops@mynextdeveloper.com" className="link">
                ops@mynextdeveloper.com
              </a>
              <br />
              <strong className="text-navy">Subject line:</strong> &ldquo;Webinar
              Data Request&rdquo;
            </address>
          </Section>

          <div className="mt-12 border-t border-navy/10 pt-6 text-[13px] text-[#444443]/60">
            This document was last updated in May 2026 and supersedes all prior
            versions. MND Technologies Private Limited &nbsp;·&nbsp;{" "}
            <a href="mailto:ops@mynextdeveloper.com" className="link">
              ops@mynextdeveloper.com
            </a>{" "}
            &nbsp;·&nbsp;{" "}
            <a
              href="https://mynextdeveloper.com"
              target="_blank"
              rel="noopener"
              className="link"
            >
              mynextdeveloper.com
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}

function Part({ label, title }: { label: string; title: string }) {
  return (
    <div className="rounded-xl bg-navy px-5 py-4">
      <p className="mb-0.5 text-[10px] font-semibold uppercase tracking-[0.18em] text-white/50">
        {label}
      </p>
      <h2 className="m-0 font-serif text-[22px] font-medium text-white md:text-[26px]">
        {title}
      </h2>
    </div>
  );
}

function Section({
  id,
  title,
  children,
}: {
  id: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <h2 className="mb-3 font-sans text-[16px] font-semibold text-navy md:text-[17px]">
        <span className="mr-2 text-teal">{id}.</span>
        {title}
      </h2>
      <div className="space-y-3 text-[#444443]">{children}</div>
    </div>
  );
}
